#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: automount
# REQUIRE: root
# BEFORE: FILESYSTEMS
# KEYWORD: nojail

. /etc/rc.subr

name="automount"
rcvar="autofs_enable"
start_cmd="automount_start"
stop_cmd="automount_stop"
required_modules="autofs"

automount_start()
{

	/usr/sbin/automount
}

rctl_stop()
{

	/sbin/umount -At autofs
}

load_rc_config $name
run_rc_command "$1"
