#!/bin/sh

if [ $# -eq 0 ]; then
	getent hosts | awk '{ print $2 }' | sort -u
	exit 0
fi

showmount -e "$1" | awk -v host="$1" \
    'NR > 1 { printf "%s\t%s:%s ", $1, host, $1 } END { printf "\n" }'

